export const MAIN_CONTAINER_ID = 'soundcloud-app';

export const FETCH_CLIENT_ID = 'FETCH_CLIENT_ID';
export const FETCH_LAST_SONGS = 'FETCH_LAST_SONGS';
export const FETCH_SONGS_BY_GENRE = 'FETCH_SONGS_BY_GENRE';

export const SONGS_LOADED = 'SONGS_LOADED';
export const ERROR_SONGS_LOADING = 'ERROR_SONGS_LOADING';

export const ERROR_CLIENT_ID_LOADING = 'ERROR_CLIENT_ID_LOADING';
