export const MAIN_CONTAINER_ID = 'soundcloud-app';

export const FETCH_CLIENT_ID = 'FETCH_CLIENT_ID';
export const FETCH_LAST_SONGS = 'FETCH_LAST_SONGS';
export const FETCH_SONGS_BY_GENRE = 'FETCH_SONGS_BY_GENRE';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const PLAY = 'PLAY';
export const TRACK_STARTED_PLAYING = 'TRACK_STARTED_PLAYING';
export const TRACK_STOPPED = 'TRACK_STOPPED';
export const TRACK_CHANGES_POSITION = 'TRACK_CHANGES_POSITION';

export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const SONGS_LOADED = 'SONGS_LOADED';
export const ERROR_SONGS_LOADING = 'ERROR_SONGS_LOADING';

export const CLIENT_ID_LOADED = 'CLIENT_ID_LOADED';
export const ERROR_CLIENT_ID_LOADING = 'ERROR_CLIENT_ID_LOADING';
