export const MAIN_CONTAINER_ID = 'soundcloud-app';

export const FETCH_CLIENT_ID = 'FETCH_CLIENT_ID';
export const FETCH_LAST_SONGS = 'FETCH_LAST_SONGS';

export const SONGS_LOADED = 'SONGS_LOADED';
export const ERROR_SONGS_LOADING = 'ERROR_SONGS_LOADING';

export const CLIENT_ID_LOADED = 'CLIENT_ID_LOADED';
export const ERROR_CLIENT_ID_LOADING = 'ERROR_CLIENT_ID_LOADING';
